// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "国民体制监测系统API",
    "title": "国民体制监测系统",
    "version": "0.0.1"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "paths": {
    "/v1/login": {
      "post": {
        "security": [],
        "description": "用户登陆",
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "user"
        ],
        "summary": "用户登陆",
        "operationId": "Login",
        "parameters": [
          {
            "type": "string",
            "description": "用户名",
            "name": "username",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "密码",
            "name": "password",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Token"
            }
          }
        }
      }
    },
    "/v1/logout": {
      "post": {
        "security": [],
        "description": "用户登出",
        "tags": [
          "user"
        ],
        "summary": "用户登出",
        "operationId": "Logout",
        "responses": {
          "200": {
            "description": "A successful response."
          }
        }
      }
    },
    "/v1/oauth/token": {
      "post": {
        "security": [],
        "description": "权限认证",
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "oauth"
        ],
        "summary": "权限认证",
        "operationId": "Token",
        "parameters": [
          {
            "type": "string",
            "description": "用户名",
            "name": "username",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "密码",
            "name": "password",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "default": "password",
            "description": "认证类型",
            "name": "grant_type",
            "in": "formData",
            "required": true
          },
          {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "参数",
            "name": "scope",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Token"
            }
          }
        }
      }
    },
    "/v1/user": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "root"
            ]
          }
        ],
        "description": "获取当前用户信息",
        "tags": [
          "user"
        ],
        "summary": "获取当前用户信息",
        "operationId": "GetUserInfo",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "root"
            ]
          }
        ],
        "description": "创建用户",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "创建用户",
        "operationId": "CreateUser",
        "parameters": [
          {
            "description": "用户信息",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "root"
            ]
          }
        ],
        "description": "修改密码",
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "user"
        ],
        "summary": "修改密码",
        "operationId": "ModifyUserPassword",
        "parameters": [
          {
            "type": "string",
            "description": "用户名",
            "name": "username",
            "in": "query"
          },
          {
            "type": "string",
            "description": "原始密码",
            "name": "old_password",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "新密码",
            "name": "new_password",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "ok"
          }
        }
      }
    },
    "/v1/user/{id}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "root"
            ]
          }
        ],
        "description": "获取单个用户的详细信息",
        "tags": [
          "user"
        ],
        "summary": "获取用户信息",
        "operationId": "GetUser",
        "parameters": [
          {
            "type": "string",
            "description": "用户ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "root"
            ]
          }
        ],
        "description": "编辑单个用户信息",
        "tags": [
          "user"
        ],
        "summary": "编辑用户",
        "operationId": "UpdateUser",
        "parameters": [
          {
            "type": "string",
            "description": "用户ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "用户参数",
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "OAuth2": [
              "root"
            ]
          }
        ],
        "description": "删除单个用户",
        "tags": [
          "user"
        ],
        "summary": "删除用户",
        "operationId": "DeleteUser",
        "parameters": [
          {
            "type": "string",
            "description": "用户ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      }
    },
    "/v1/users": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "root"
            ]
          }
        ],
        "description": "获取用户列表",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "获取用户列表",
        "operationId": "GetUsers",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "翻过条目数",
            "name": "skip",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "限制条目数",
            "name": "limit",
            "in": "query"
          },
          {
            "type": "string",
            "description": "筛选条件",
            "name": "query",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/Users"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Principal": {
      "description": "OAuth2鉴权信息",
      "type": "object",
      "properties": {
        "id": {
          "description": "用户ID(唯一)",
          "type": "string",
          "x-omitempty": false
        },
        "name": {
          "description": "用户名(唯一)",
          "type": "string",
          "x-omitempty": false
        },
        "role": {
          "description": "当前角色",
          "type": "string",
          "x-omitempty": false
        }
      }
    },
    "Token": {
      "type": "object",
      "properties": {
        "access_token": {
          "description": "jwt token",
          "type": "string",
          "x-omitempty": false
        },
        "expires_at": {
          "description": "token过期时间(timestamp)",
          "type": "string",
          "x-omitempty": false
        },
        "expires_in": {
          "description": "token过期时间(秒)",
          "type": "string",
          "x-omitempty": false
        },
        "token_type": {
          "description": "token的类型",
          "type": "string",
          "default": "Bearer",
          "x-omitempty": false
        }
      }
    },
    "User": {
      "description": "用户信息",
      "type": "object",
      "properties": {
        "email": {
          "description": "邮箱",
          "type": "string",
          "x-omitempty": false
        },
        "id": {
          "type": "string",
          "x-omitempty": false,
          "readOnly": true
        },
        "name": {
          "description": "用户名",
          "type": "string",
          "x-omitempty": false
        },
        "phone": {
          "description": "电话号码",
          "type": "string",
          "x-omitempty": false
        },
        "ps": {
          "description": "用户密码",
          "type": "string",
          "x-omitempty": false
        },
        "role": {
          "description": "用户角色",
          "type": "string",
          "enum": [
            "student",
            "teacher",
            "data_entry"
          ],
          "x-omitempty": false
        }
      }
    },
    "Users": {
      "description": "用户列表",
      "type": "object",
      "properties": {
        "items": {
          "description": "用户列表",
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          },
          "x-omitempty": false
        },
        "total_count": {
          "description": "所有用户总数",
          "type": "integer",
          "format": "int64",
          "x-omitempty": false
        }
      }
    }
  },
  "securityDefinitions": {
    "BasicAuth": {
      "type": "basic"
    },
    "OAuth2": {
      "type": "oauth2",
      "flow": "password",
      "tokenUrl": "http://localhost:8080/v1/oauth/token",
      "scopes": {
        "root": "资料录入员",
        "teacher": "老师"
      }
    }
  },
  "security": [
    {
      "OAuth2": [
        "teacher",
        "root"
      ]
    }
  ],
  "tags": [
    {
      "description": "认证管理",
      "name": "oauth"
    },
    {
      "description": "用户管理",
      "name": "user"
    }
  ],
  "externalDocs": {
    "description": "Find out more about Swagger",
    "url": "https://github.com/kaisawind/iotx"
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "国民体制监测系统API",
    "title": "国民体制监测系统",
    "version": "0.0.1"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "paths": {
    "/v1/login": {
      "post": {
        "security": [],
        "description": "用户登陆",
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "user"
        ],
        "summary": "用户登陆",
        "operationId": "Login",
        "parameters": [
          {
            "type": "string",
            "description": "用户名",
            "name": "username",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "密码",
            "name": "password",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Token"
            }
          }
        }
      }
    },
    "/v1/logout": {
      "post": {
        "security": [],
        "description": "用户登出",
        "tags": [
          "user"
        ],
        "summary": "用户登出",
        "operationId": "Logout",
        "responses": {
          "200": {
            "description": "A successful response."
          }
        }
      }
    },
    "/v1/oauth/token": {
      "post": {
        "security": [],
        "description": "权限认证",
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "oauth"
        ],
        "summary": "权限认证",
        "operationId": "Token",
        "parameters": [
          {
            "type": "string",
            "description": "用户名",
            "name": "username",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "密码",
            "name": "password",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "default": "password",
            "description": "认证类型",
            "name": "grant_type",
            "in": "formData",
            "required": true
          },
          {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "参数",
            "name": "scope",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Token"
            }
          }
        }
      }
    },
    "/v1/user": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "root"
            ]
          }
        ],
        "description": "获取当前用户信息",
        "tags": [
          "user"
        ],
        "summary": "获取当前用户信息",
        "operationId": "GetUserInfo",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "root"
            ]
          }
        ],
        "description": "创建用户",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "创建用户",
        "operationId": "CreateUser",
        "parameters": [
          {
            "description": "用户信息",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "root"
            ]
          }
        ],
        "description": "修改密码",
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "user"
        ],
        "summary": "修改密码",
        "operationId": "ModifyUserPassword",
        "parameters": [
          {
            "type": "string",
            "description": "用户名",
            "name": "username",
            "in": "query"
          },
          {
            "type": "string",
            "description": "原始密码",
            "name": "old_password",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "新密码",
            "name": "new_password",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "ok"
          }
        }
      }
    },
    "/v1/user/{id}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "root"
            ]
          }
        ],
        "description": "获取单个用户的详细信息",
        "tags": [
          "user"
        ],
        "summary": "获取用户信息",
        "operationId": "GetUser",
        "parameters": [
          {
            "type": "string",
            "description": "用户ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "OAuth2": [
              "root"
            ]
          }
        ],
        "description": "编辑单个用户信息",
        "tags": [
          "user"
        ],
        "summary": "编辑用户",
        "operationId": "UpdateUser",
        "parameters": [
          {
            "type": "string",
            "description": "用户ID",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "用户参数",
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "OAuth2": [
              "root"
            ]
          }
        ],
        "description": "删除单个用户",
        "tags": [
          "user"
        ],
        "summary": "删除用户",
        "operationId": "DeleteUser",
        "parameters": [
          {
            "type": "string",
            "description": "用户ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      }
    },
    "/v1/users": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "root"
            ]
          }
        ],
        "description": "获取用户列表",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "获取用户列表",
        "operationId": "GetUsers",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "翻过条目数",
            "name": "skip",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "限制条目数",
            "name": "limit",
            "in": "query"
          },
          {
            "type": "string",
            "description": "筛选条件",
            "name": "query",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/Users"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Principal": {
      "description": "OAuth2鉴权信息",
      "type": "object",
      "properties": {
        "id": {
          "description": "用户ID(唯一)",
          "type": "string",
          "x-omitempty": false
        },
        "name": {
          "description": "用户名(唯一)",
          "type": "string",
          "x-omitempty": false
        },
        "role": {
          "description": "当前角色",
          "type": "string",
          "x-omitempty": false
        }
      }
    },
    "Token": {
      "type": "object",
      "properties": {
        "access_token": {
          "description": "jwt token",
          "type": "string",
          "x-omitempty": false
        },
        "expires_at": {
          "description": "token过期时间(timestamp)",
          "type": "string",
          "x-omitempty": false
        },
        "expires_in": {
          "description": "token过期时间(秒)",
          "type": "string",
          "x-omitempty": false
        },
        "token_type": {
          "description": "token的类型",
          "type": "string",
          "default": "Bearer",
          "x-omitempty": false
        }
      }
    },
    "User": {
      "description": "用户信息",
      "type": "object",
      "properties": {
        "email": {
          "description": "邮箱",
          "type": "string",
          "x-omitempty": false
        },
        "id": {
          "type": "string",
          "x-omitempty": false,
          "readOnly": true
        },
        "name": {
          "description": "用户名",
          "type": "string",
          "x-omitempty": false
        },
        "phone": {
          "description": "电话号码",
          "type": "string",
          "x-omitempty": false
        },
        "ps": {
          "description": "用户密码",
          "type": "string",
          "x-omitempty": false
        },
        "role": {
          "description": "用户角色",
          "type": "string",
          "enum": [
            "student",
            "teacher",
            "data_entry"
          ],
          "x-omitempty": false
        }
      }
    },
    "Users": {
      "description": "用户列表",
      "type": "object",
      "properties": {
        "items": {
          "description": "用户列表",
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          },
          "x-omitempty": false
        },
        "total_count": {
          "description": "所有用户总数",
          "type": "integer",
          "format": "int64",
          "x-omitempty": false
        }
      }
    }
  },
  "securityDefinitions": {
    "BasicAuth": {
      "type": "basic"
    },
    "OAuth2": {
      "type": "oauth2",
      "flow": "password",
      "tokenUrl": "http://localhost:8080/v1/oauth/token",
      "scopes": {
        "root": "资料录入员",
        "teacher": "老师"
      }
    }
  },
  "security": [
    {
      "OAuth2": [
        "teacher",
        "root"
      ]
    }
  ],
  "tags": [
    {
      "description": "认证管理",
      "name": "oauth"
    },
    {
      "description": "用户管理",
      "name": "user"
    }
  ],
  "externalDocs": {
    "description": "Find out more about Swagger",
    "url": "https://github.com/kaisawind/iotx"
  }
}`))
}
